// <auto-generated />
using EmployeeBenefits.Data.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EmployeeBenefits.Data.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20220309033045_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("EmployeeBenefits.Data.Model.Dependent", b =>
                {
                    b.Property<int>("DependentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Dependent_Id")
                        .UseIdentityColumn();

                    b.Property<int>("DependentTypeId")
                        .HasColumnType("int")
                        .HasColumnName("Dependent_Type_Id");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int")
                        .HasColumnName("Employee_Id");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("First_Name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Last_Name");

                    b.HasKey("DependentId");

                    b.HasIndex("DependentTypeId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Dependent");
                });

            modelBuilder.Entity("EmployeeBenefits.Data.Model.DependentTypeLkp", b =>
                {
                    b.Property<int>("DependentTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Dependent_Type_Id")
                        .UseIdentityColumn();

                    b.Property<string>("DependentTypeName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Dependent_Type_Name");

                    b.Property<bool>("Obsolete")
                        .HasColumnType("bit");

                    b.HasKey("DependentTypeId")
                        .HasName("PK__Dependen__B35DA9EE1C2863C3");

                    b.ToTable("Dependent_Type_Lkp");
                });

            modelBuilder.Entity("EmployeeBenefits.Data.Model.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Employee_Id")
                        .UseIdentityColumn();

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("First_Name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Last_Name");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18,0)");

                    b.HasKey("EmployeeId");

                    b.ToTable("Employee");
                });

            modelBuilder.Entity("EmployeeBenefits.Data.Model.Dependent", b =>
                {
                    b.HasOne("EmployeeBenefits.Data.Model.DependentTypeLkp", "DependentType")
                        .WithMany("Dependent")
                        .HasForeignKey("DependentTypeId")
                        .HasConstraintName("FK_Dependent_Dependent_Type")
                        .IsRequired();

                    b.HasOne("EmployeeBenefits.Data.Model.Employee", "Employee")
                        .WithMany("Dependent")
                        .HasForeignKey("EmployeeId")
                        .HasConstraintName("FK_Dependent_Employee")
                        .IsRequired();

                    b.Navigation("DependentType");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("EmployeeBenefits.Data.Model.DependentTypeLkp", b =>
                {
                    b.Navigation("Dependent");
                });

            modelBuilder.Entity("EmployeeBenefits.Data.Model.Employee", b =>
                {
                    b.Navigation("Dependent");
                });
#pragma warning restore 612, 618
        }
    }
}
